version: "3.3"

services:

  api:
    build:
      context: .
    image: backendteszt
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - internal

  users:
    build:
      context: .
    env_file: docker-compose.env
    environment:
      SERVICES: users
    depends_on:
      - redis
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal
    expose:
      - "27017"
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    networks:
      - internal

networks:
  internal:

volumes:
  data:
